=== claudius108/kuberam-xml-plugin/src/test/resources/ro/kuberam/maven/plugins/xml/mojos/process-xinclude/sanskrit-neu3.dtd
<!ELEMENT b (#PCDATA | u | label | pb | sup | q1 |ref | q2)*>
<!ELEMENT u (#PCDATA | sup | q1 |ref | q2)*>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT label (#PCDATA)>
	
<!ELEMENT q2 (#PCDATA | ref | q1 | b | u | sup |note | pb | fw | lg )*>
<!ELEMENT fw (#PCDATA)>
<!ELEMENT q1 (#PCDATA | ref | note | pb | b| u | sup | fw | lg)*>
<!ELEMENT div (#PCDATA | p | lg | note | pb | fw | q2 | label)*>
<!ATTLIST div type CDATA #IMPLIED>
<!ELEMENT l (#PCDATA | ref | b | u | sup | q1 | q2 | label)* >
<!ELEMENT section (#PCDATA | head | pb |lg| fw | div | section)*>
<!ATTLIST section id CDATA #IMPLIED>
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref n CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT pb (#PCDATA)>
<!ATTLIST pb n CDATA #IMPLIED>
<!ELEMENT lg (l | pb | fw| note)*>
<!ATTLIST lg n CDATA #IMPLIED>
<!ATTLIST lg type CDATA #IMPLIED>
<!ELEMENT p (#PCDATA | q1 | ref | q2 | b | u | sup | note | pb | fw | label)*>
<!ATTLIST p rend CDATA #IMPLIED >
<!ELEMENT report (#PCDATA | title | subtitle | section)*>
<!ATTLIST report id CDATA #IMPLIED>
<!ATTLIST report pubid CDATA #IMPLIED>
<!ATTLIST report publish CDATA #IMPLIED>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT head (#PCDATA|q1)*>
<!ELEMENT note (#PCDATA | p)*>
<!ATTLIST note target CDATA #IMPLIED>

=== claudius108/kuberam-xml-plugin/src/test/resources/ro/kuberam/maven/plugins/xml/mojos/process-xinclude/document-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE div SYSTEM "src/test/resources/ro/kuberam/maven/plugins/xml/mojos/process-xinclude/sanskrit-neu3.dtd">
<div>
	<p>
		नमो विघ्घ्नप्रमथनाय ॥
		<label>1b</label>
	</p>
	<lg>
		<l>नानासद्गुणरत्नराशिकिरणध्वस्तान्धकारस्सदा (,)</l>
		<l>यो नानाविधसत्त्ववांछितफलप्राप्त्यर्थमत्त्युद्यतः ।</l>
		<l>
			तन्निःशेषजगद्धितोदयपरन्नत्वार्यमञ्जुश्रियं ।
			<sup>1</sup>
		</l>
		<l>वादन्यायविभाग एष विमलः सङ्क्षिप्त आरभ्यते ॥ (1)</l>
	</lg>
	<p>
		यत्प्रयोजनरहितं तत्प्रेक्षापूर्व्वकारिभिर्न्नारभ्यते । यथा बलित्वग्दर्शन-
		विनिश्चयादिकं । अप्रयोजनञ्चेदं
		प्रकरण
		<sup>2</sup>
		मित्याशंकावतस्तदाशंकापरिजिहीर्षया
		प्रयोजनप्रदर्शनाय
		<b>न्यायवादिन</b>
		(1b1) मित्यादिवाक्यमुपन्यस्तवान् । कथम्पु-
		नरनेन वाक्येनास्य प्रयोजनमुपदर्श्यत इत्यास्तां
		<sup>3</sup>
		तावदेतद् । अर्थस्तु
		व्याख्यायते ॥ न्यायस्त्रिरूपलिङ्गलक्षणा युक्तिः । नीयते प्राप्यते विवक्षितार्थ-
		सिद्धिरनेनेति कृत्त्वा अत एव
		<b>त्रिविधं</b>
		लिङ्गमि (1b2) त्यादिना त्रि
		<sup>4</sup>
		रूपमेव
		लिङ्गमनन्तरम्वक्ष्यति । तदभिधायि वचनमित्यपरे । तम्वदितुं शीलं यस्य स
		तथोक्तः । तमपि निगृह्णन्ति
		पराजयन्त इत्यर्थः । निगृह्णन्तु नामान्याय
		<sup>5</sup>
		-
		वादिनम्पराजयाधिकरणत्त्वादेव । न्यायवादिनन्त्वनिग्रहार्हमपि यन्निगृह्णन्त्ये-
		तन्न सम्भाव्यते ।
		परोत्कर्षव्यारोपधियस्तु तमपि पराजयन्त इति सम्भावना
		<sup>6</sup>
		-
		यामपि शब्दः समुच्चयार्थोऽतिशयद्योतनार्थो वा केषु (|) निगृह्णन्तीत्याह ।
		<b>वादेषु</b>
		(1b1) साधनदूषणसंशब्दितेषु विचारेष्विति यावत् ।
		<b>विवादेष्विति</b>
		क्वचित्पाठः ।
		<sup>7</sup>
		तत्र विरुद्धा वादा
		<b>विवादा</b>
		स्तेष्विति व्याख्येयं ।
		विरुद्वाश्च कथं (|) साधनदूषणसंशब्दितानाम्विचाराणान्तद्विरुद्धार्थसाधन-
		प्रवृत्तत्त्वात् ॥ कथम्पुनर्न्यायवादिनमसत्स्वसि
		<sup>8</sup>
		द्ध्यादिषु हेतुदोषेषु निगृह्णन्ती
		त्याह ॥
		<b>असद्व्ययवस्थोपन्यासैः</b>
		। (1b1) असतामसाधूनाम्व्यवस्थाः । असत्यो

		<pb n="2" />

		वा व्यवस्थाः सद्भिः कुत्सितत्त्वात् । ताश्च फलजात्यसन्निग्रहस्थान-
		<label>2a</label>
		लक्ष
		<sup>9</sup>
		णास्तासामुपन्यासाः । प्रयोगस्तैरिति विग्रहः । के पुनरह्रीकास्त एवं
		विधा इत्याह ॥ शठा धूर्ता मायाविनः
		परसम्पत्तावीर्ष्यालव इति यावत् ।
		यस्मात्तं तथा निगृह्णन्ति
		<sup>1</sup>
		इति तस्मात्तन्निषेधार्थं तेषां शठानान्तेषाम्वा
		ऽसद्व्यवस्थोपन्यासानान्तस्य
		<b>वा</b>
		निग्रहस्य त्रयाणां
		<b>वा</b>
		निषेधो निरासस्तदर्थन्तन्नि-
		मित्तमिदम्प्रकरणमारभ्यते ॥
		<b>स ए</b>
		वार्थोऽस्ये
		<sup>2</sup>
		ति विग्रहीतव्यं । तन्निषेधे च
		कृते सम्यग्विचारः प्रवर्तते तत्पूर्वकश्च सर्वः पुरुषार्थ इत्यभिप्रायः ।
		आसन्न-
		विषयिणा त्वन्तर्विपरिवर्त्ति प्रकरणमिदमापरा
		<sup>3</sup>
		मृषति । अन्तस्तन्त्वात्मना
		परिनिष्पन्नत्वात् । अन्यथाऽपरिनिष्पन्नात्मतयाऽसन्नत्वाभावादिदम् शब्द-
		प्रयोगो न
		स्यात् ।
		<b>आरभ्यत</b>
		(1b1) इति वर्तमानकालनिर्देशः (|)
		<b>
			क
			<sup>4</sup>
		</b>
		थमिति चेत् ।
		<b>वर्तमानसामीप्ये वर्तमानवद्वे (पाणिनिः (3|3|31)</b>
		ति वचनात्
		सम्बन्धोऽप्यभिधानीय एवान्यथा बालोन्मत्तप्रलापवदग्राह्यमिदं प्रेक्षापूर्वकारिणा-
		म्भवेदिति चेत्
		<sup>5</sup>
		सत्त्यमेतत् । प्रयोजनान्तर्गतत्त्वात् पृथ
		<b>ग</b>
		सौ नाभिहितः । तथाहि
		<b>तन्निषेधार्थमिदमारभ्यते</b>
		(1b1) ततश्चैतत्प्रयोजनमनेन प्रकरणेन साध्यते ।
		तथा च प्रयोजनप्रकरण
		<sup>6</sup>
		योः साध्यसाधनलक्षणः सम्बन्ध इति सूचितं । ये त्वन्ये
		क्रियानन्तर्यादिलक्षणाः सम्बन्धास्ते न वाच्या एव
		प्रकरणक्रियायामनङ्गभू-
		तत्त्वात् । तथाहि तेषु सत्स्वपि प्रयो
		<sup>7</sup>
		जनाभावे नारभ्यत एव प्रकरणं ।
		असत्स्वपि च तेषु सति प्रयोजने प्रारभ्यत एव । तस्मात्प्रकरणारम्भस्य
		प्रयोजनान्वयव्यतिरेकानुविधानात्प्रयोजनमेवाभिधानी
		<sup>8</sup>
		यम्प्रेक्षापूर्वकारिणा । तस्मिं-
		श्चाभिहिते सम्बन्धोप्युक्त एव भवतीति मन्यते । नानवधारितप्रकरण
		<label>2b</label>
		शरीराः प्रवर्तन्ते प्रेक्षावन्तस्तस्मात्प्रयोजनवत्प्रवृत्त्यङ्गत्वात्प्रकरण
		<sup>9</sup>
		शरीरमपि
		वक्त्व्यमेवेति चेत् । एवमेतत्प्रयोजनवाक्येन त्वभिहितत्वान्नैव तदपि सम्बन्धव-
		त्पृथगभिधानमर्हति ।
		यतस्तन्निषेधार्थमिदमारभ्यत इत्युक्तमतश्च तत्
		<sup>1</sup>
		निषे
		धोऽस्य शरीरमित्युक्तम्भवति । यदा चैतन्निषेधार्थमिदमारभ्यते तदा पूर्वको हेतु-
		रसिद्धः ।
		प्रतिप्रमाणद्वयञ्चानेन सूचितं प्रारब्धव्यमिदम्प्रकरणम्प्रेक्षावता
		<sup>2</sup>
		सति
		सामर्थ्ये । ग्राह्यम्वा प्रयोजनवत्वात् । सम्बन्धवत्वाच्च तदन्यशास्त्रवदिति
		स्वभावहेतुः ।
	</p>
	<!-- <note target='2-1'><p>न्यायवार्तिकतात्पर्यटीकायां [५।२।१ (pR0 697, 723)], न्याय- मञ्जर्यां [४।२।१ (pR0 
		639)]च सोद्धरणं अस्य खंडनम् ।</p></note> -->

	<pb n="3" />

	<p>
		एवमभिधाय प्रयोजनं सकलप्रकरणार्थसंग्राहकं श्लोकमाह
		<sup>3</sup>
		<b>असाधनाङ्वचन</b>
		(1b1) मित्यादिना । असाधनाङ्गवचनमदोषोद्भावनञ्च द्वयोर्वादिप्रतिवादि
		नोर्यथाक्रमं निग्रहस्थानं पराजयाधिकरणं ।
		अन्यत्त्वित्येत
		<sup>4</sup>
		द्धेयव्यतिरिक्तम-
		<b>क्षपादप</b>
		रिकल्पितं प्रतिज्ञासंन्यासादिकं वक्ष्यमाणं निग्रहस्थानं न
		<b>युक्तमिति</b>
		कृत्वा
		<b>नेष्यते</b>
		(|) निग्रहस्थानमिति वर्त्तते । अयं तावत् स
		<sup>5</sup>
		मासेन श्लोकार्थः ।
		<b>इष्टस्ये</b>
		(1b1) त्यादिना विभागमारभते । इष्टोऽर्थोऽनित्त्यः शब्द इत्यादि
		साध्यत्त्वेनेप्सितः । तस्य
		<b>सिद्धिः</b>
		प्रतिपत्तिः साधनं । तदनेन भावस्य
		<sup>6</sup>
		साधनोयं साधनशब्दस्तावदस्मिन्व्याख्यानेऽभिप्रेतो न तु करणसाधन इति
		दर्शयति ॥ तस्य
		साधनस्येष्टार्थसिद्धिलक्षणमस्याङ्गं किन्तदित्याह ।
		<b>निर्वर्त्तकं</b>
		जनकं । अने
		<sup>7</sup>
		नाङ्गशब्दं व्याचष्टे । कारणपर्यायोयमत्राङ्गशब्दो नावयवपर्याय
		इत्यर्थः । तच्च साधनाङ्गमिह निश्चितत्रैरूप्यं
		लिङ्गमुच्यते । अस्य साधनाङ्गस्य
		वचनं त्रिरूपलिङ्गा
		<sup>8</sup>
		ख्यानं । तस्य
		<b>साधनाङ्गस्यावचनमनुच्चारणम</b>
		(1b2)
		नभिधानं यत्तदसाधनाङ्गवचनं । अनेनैतत्कथयति असाधनाङ्गस्य पक्षोपनयना-
		देर्वचनमसाधनाङ्गवचनमिति नै
		<sup>9</sup>
		व प्रतिपत्तव्यमस्मिन्व्याख्याने । किन्तु साधनाङ्ग-
		स्यैवावचनमसाधनाङ्गवचनमिति । तदसाधनाङ्गवचनं वादिनो
		निग्रहस्थानं ।
		तदेतेन श्लोकस्य पूर्व्वभागम्विवृणोति । कथम्पुनः साधनाङ्गस्यानुच्चारणम्भवति
		<b>निग्रहस्थानं</b>
		चेत्याह ।
		<b>तदभ्युपगम्येति</b>
		(1b2) तदितीष्टं साध्यमभ्युपगम्याह-
		मेतत्साधयामीति प्रतिज्ञयाप्रतिभया करण
		<sup>2</sup>
		भूतया तूष्णीम्भावात् । अप्रतिभाऽत्र
		पूर्व्वाधिगतार्थविस्मरणं स्तम्भितत्त्वञ्च गृह्यते ।
	</p>
	<p>
		अनेन सर्व्वथा साधनाङ्गस्यावचनमाह अभिधाने वा यदि न समर्थितं तदोक्त-
		मप्यऽ
		<sup>3</sup>
		नूक्तमेव स्वकार्याकरणात् । इत्यभिप्रायवानाह (--)
		<b>साधनाङ्गस्या-
			समर्थनाद्वेति
		</b>
		(1b2) । तदभ्युपगम्येतिवर्तते । वा शब्दः पुर्व्वापेक्षया
		विकल्पार्थः । साधना
		<sup>4</sup>
		ङ्गस्यासमर्थनं त्रिष्वपि रूपेषु निश्चयाप्रदर्शनं । तस्मात्तू-
		ष्णीम्भावादसमर्थनाच्च साधनाङ्गस्यानुच्चारणं ।
		ततश्च प्रतिज्ञातार्थाकारणात्
		वादिनो
		<sup>5</sup>
		<b>निग्रहाधिकरण</b>
		मिति (1b2) प्रकृतेन सम्बन्धः । क्वचित्तु
		<b>वादिन</b>
		इति पाठः । तत्र तच्छब्देन प्रकृतमनुच्चारणं संबध्यते ।
	</p>
	<p>
		कथम्पुनः साधनाङ्गासमर्थनम्भ
		<sup>6</sup>
		वति । येन तद्विपर्ययेनासमर्थनात्प्रति-
		ज्ञातार्थाकारणाद्वादिनो निग्रहाधिकरणत्त्वमिति कदाचित्कश्चिद्
		ब्रूयादित्येतत्परि-
		जिहीर्षुरादिप्रस्थानमारचयति
		<sup>7</sup>
		<b>त्रिविधमेवे</b>
		(1b2) त्यादिना त्रिप्रकारमेव लिङ्ग-

		<pb n="4" />

		मङ्गङ्करणं कस्यासिद्धेः प्रतिपत्तिरूपायाः । कस्य सिद्धेरित्याह ।
		<b>अप्रत्य-
			क्षस्या
		</b>
		परोक्षस्यानुमेयभूतस्य वस्तुन इति
		<sup>8</sup>
		यावत् । अवधारणञ्चतुरादि
		व्यवच्छेदमाचष्टे ।
		<b>त्रिविधमेवेति</b>
		नियमः कथमयमिति चेत् । यस्माद्विधि
		<label>3b</label>
		प्रतिषेधरूपतया द्विधा साध्यं व्यवस्थितं । विधिरूपञ्च सद्भा
		<sup>9</sup>
		वरूपङ्कारणरू
		पम्वा भवद् भवेत् । नान्यत् । तत्र हेतोः प्रतिबन्धायोगात् । नह्यर्थान्तरस्याका-
		र्यस्य
		सद्भावेऽपरस्य सद्भावो युक्तः । पटसद्भाव इवोष्ट्रस्य । नाप्यर्थां
		<sup>1</sup>
		तरस्याकारणस्य निवृत्तावकार्यस्यान्यस्य च निवृत्तिर्युक्तिमती । उष्ट्रे निवृत्ताविव
		पटस्य । न
		चान्वयव्यतिरेकविकलस्यागमकत्त्वं युक्तं । पटस्याप्युष्ट्रगमकत्त्व
		<sup>2</sup>
		-
		प्रसङ्गात् । स्वभावभूतधर्मसद्भावे तु स्वभावभूतस्यान्यस्य सद्भावो युक्तो नहि
		स्वभावः स्वम्भावम्परित्यज्य
		वर्त्ते । तत्स्वभावत्त्वाभावप्रसङ्गात् । तन्निवृत्तौ-
		च निवृ
		<sup>3</sup>
		त्तिः ॥ कार्यस्यापि भावे कारणस्य भावो युक्तः । तन्निवृत्तौ च
		निवृत्तिरन्यथा तेन विनापि भावात्कार्यमेव
		तत्तस्य न स्यात्तदन्यवत् ।
		तस्मात्स्वभाव
		<sup>4</sup>
		कारणभूतसाध्यभेदात् । द्विधैव विधिरूपं साध्यं तत्रैव हेतोः
		प्रतिबन्धात् । स्वभावभूतञ्च साध्यं स्वभावहेतुः
		साधयति । कारणभूतञ्च
		कार्यहेतु
		<sup>5</sup>
		रित्यभ्युपेयं । प्रतिषेधमप्युपलब्धिलक्षणप्राप्तानुपलब्धिरेव साधयति ।
		नान्या यथा तथा विस्तरेण
		प्रतिपादयिष्यति । तदिदमिह संक्षिप्तमर्थ
		<sup>6</sup>
		तत्त्वं
		विषयव्यपेक्षया विषयिणो लिंगस्य व्यवस्था । विषयश्च विधिः प्रतिषेधो वा
		भवेत् । विधावप्यर्थान्तरम्वा
		विधीये तानर्थान्तरं वा अर्थान्तरविधावपि का
		<sup>7</sup>
		-
		र्यकारणमनुभयम्वा साध्यते । कार्यप्रतिपादनेपि कारणसामान्यम्वाऽमेघादि-
		व्यावृत्तं वस्तुमात्रं
		लिङ्गत्वेनोच्यते । कारणविशेषो वा योऽप्रति-
		बद्धसामर्थ्ये मे
		<sup>8</sup>
		घादिः । प्रतिषेधोपि निषेध्याभिमतस्यानुपलम्भेनोपलम्भेन
		वा प्रतिपाद्येत । अनुपलम्भेपि
		उपलम्भनिवृत्तिमात्रलक्षणो वा भवेत् ।
		<label>4a</label>
		तत्तुल्ययोगावस्थ(ः) केवला
		<sup>9</sup>
		परपदार्थोपलम्भरूपो वेति विकल्पाः । तत्र-
		नावश्यं गम्भीरध्वानादियुक्तमपि मेघादिकारणमात्रं
		वृष्ट्यादिकार्याविर्भावक-
		मन्तरा प्रतिबन्धसम्भवेन व्य
		<sup>1</sup>
		भिचारात् । अतो न कारणमात्रं गमकं । कारण-
		विशेषादप्यप्रतिहतशक्तेरनन्तरं
		सम्बन्धस्मृतिव्यवहितादनुमेयविज्ञानात्प्राक्
		कार्यमेवोद्भूतमक्षज्ञानग्राह्यं
		<sup>2</sup>
		भवतीति न तस्यापि लिङ्गत्वं । कार्यन्तु कारण-
		लिङ्गं युक्तं । तदविनाभावात् । तदतिक्रमे वा
		हेतुमत्ताम्विलंघयेत् । अनुभयमप्य-
		सम्बन्धानुगमकमतिप्रसङ्गो
		<sup>3</sup>
		वा । अनर्थान्तरमप्यव्यभिचाराङ्गम्यत इति युक्ति-
		मत् । निषेधोप्युपलम्भेन न युज्यते विरोधात् । कथं हि
		नामोपलभ्यते च नास्ति

		<pb n="5" />

		चेत्युपपद्यते । तज्ज्ञान
		<sup>4</sup>
		निवृत्तिमात्रमपि व्यभिचारि । एकज्ञानसंसर्गिणस्तु कैवल्य-
		दृष्टेरसत्ताव्यवहारो युक्तो यदि हि स्यादुपलभ्य
		सत्त्व एव भवेत् । प्रमाणञ्च यद-
		नुपपद्य
		<sup>5</sup>
		मानविषयं न तद्विषयि युक्तं । यथा वाजिविषाणं । अनुपपद्यमानविषय-
		ञ्चोक्तप्रकारेण स्वभावादि
		स्यादन्यसंयोग्यादिपरपरिकल्पितं लिं
		<sup>6</sup>
		गमिति व्याप-
		कानुपलम्भः । वैधर्म्येण नीलादिज्ञानं । तदेव वा कार्यादिलिङ्गं । नैमित्तिकशब्दा-
		र्थानुपपत्तिर्बाधिका । किमेवं सिद्धमगमकत्त्वमन्येषां । तथाहि विष
		<sup>7</sup>
		यित्वङ्ग-
